name: demo_environment_variables_secrets
on:
  workflow_dispatch:
env:
  WORKFLOW_ENV: gha-demo
jobs:
  test:
    environment: testing
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      VERSION: ${{ vars.VERSION }}
      PORT: 8080
    steps:
      - name: Output information
        run: |
          echo "WORKFLOW_ENV: $WORKFLOW_ENV"
          echo "VERSION: $VERSION"
          echo "USERNAME: $USERNAME"
          echo "USERNAME: $USERNAME"
          echo "${{ env.PORT }}"
  prod:
    environment: production
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      VERSION: ${{ vars.VERSION }}
      PORT: 8080
    steps:
      - name: Output information
        run: |
          echo "WORKFLOW_ENV: $WORKFLOW_ENV"
          echo "VERSION: $VERSION"
          echo "USERNAME: $USERNAME"
          echo "USERNAME: $USERNAME"
          echo "${{ env.PORT }}"
