name: Output information
on: 
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
  workflow_dispatch:
  push:
    branches:
      - main
      - dev-*
env:
  user_name: dat
jobs:
  info:
    env:
      password: 123456
    runs-on: ubuntu-latest
    steps:
      - name: Output github context
        run: | 
          echo "${{ env.user_name }}"
          echo "$user_name"
          echo "${{ env.password }}"
          echo "$password"